spring:
    application:
        # name of the application
        name: example-jobs
    # Jackson configuration for JSON serialization
    jackson:
        # Without timezone (time will be rendered in GMT)
        # date-format=com.fasterxml.jackson.databind.util.ISO8601DateFormat
        date-format: yyyy-MM-dd'T'hh:mm:ss.sssZ
        serialization:
            indent-output: true
    thymeleaf:
        cache: false

# context + port of the application
server:
    servlet:
        context-path: /
    port: 8080

management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: '*'
    endpoint:
        loggers:
            enabled: true

edison:
    # disable graceful shutdown
    gracefulshutdown:
        enabled: false
    jobs:
        mongo:
            enabled: false # enable for persistence
        status:
            calculator:
                Bar: errorOnLastThreeJobsFailed
                Foo: warningOnLastJobFailed
                default: errorOnLastJobFailed
    status:
        application:
            description: Example service to show how to use edison-jobs in your microservices
            title: Example Jobs

    # configuration for MongoDB (persistence layer)
    # mongo
    #    db: edison-example
    #    user: edison-example
    #    passwd:
    #    host: localhost
