spring:
    application:
        name: example-togglz
    jackson:
        date-format: yyyy-MM-dd'T'hh:mm:ss.sssZ
        serialization:
            indent-output: true
    thymeleaf:
        cache: false

server:
    servlet:
        context-path: /
    port: 8080

management:
    endpoints:
        web:
            base-path: /actuator
            expose: '*'

edison:
    gracefulshutdown:
        enabled: false
    mongo:
        db: edison-example
        host: localhost:27017,localhost:27018,localhost:27019
        passwd: ''
        user: edison-example
    status:
        application:
            description: Example service to show how to use edison-togglz together with edison-mongo in your microservices
            title: Example Togglz Mongo
